name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production via SSH
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/PAJ/ProjectAlijahonServer
            git fetch origin
            git reset --hard origin/master
            git remote remove origin
            git remote add origin https://github.com/ikromhoshimjonov/ProjectAlijahonServer.git
            git pull origin master
            source .venv/bin/activate
            pip install -r requirments.txt
            make mig
            sudo systemctl restart alijahon_project.service
            sudo systemctl enable alijahon_project.service
            sudo systemctl enable nginx.service
            sudo systemctl restart nginx.service
